import 'package:flutter/cupertino.dart';

class SizeConfig{
  static double WIDHT;
  static double HEIGHT;

  static double WAITING_SCREEN_MAINTITLE;
  static double WAITING_SCREEN_SUBTITLE;
  static double WAITING_SCREEN_LOGOSIZE;

  static double HOME_SCREEN_MAINTITLE;
  static double HOME_SCREEN_SUBTITLE;
  static double HOME_SCREEN_LOGOSIZE;

  static double HOME_SCREEN_OTHERLOTTERYTICKET;
  static double HOME_SCREEN_CARDTITLESIZE;

  static double HOME_SCREEN_MAINT_BLOCK;

  static double HOME_SCREEN_MAINLOTTERY;
  static double HOME_SCREEN_SUBLOTTERY;


  static double HOME_SCREEN_MAIN_CARDWIDTH;
  static double HOME_SCREEN_MAIN_BALL_SIZE;
  static double HOME_SCREEN_MAIN_NUMBER_BALL_SIZE;

  static double HOME_SCREEN_MAIN_SUBCARDWIDTH;
  static double HOME_SCREEN_MAIN_SUBBALL_SIZE;
  static double HOME_SCREEN_MAIN_SUBNUMBER_BALL_SIZE;


  static double HOME_SCREEN_LISTVIEW_BLOCK;

  static double HOME_SCREEN_FLOATBUTTON_SIZE;
  static double HOME_SCREEN_FLOATBUTTON_CONTENT_SIZE;

  SizeConfig(BuildContext context){
      SizeConfig.WIDHT = MediaQuery.of(context).size.width;
      SizeConfig.HEIGHT = MediaQuery.of(context).size.height;

      WAITING_SCREEN_MAINTITLE = WIDHT * 0.15815085; // 65.0;
      WAITING_SCREEN_SUBTITLE = WIDHT * 0.04622871; //19.0;
      WAITING_SCREEN_LOGOSIZE = WIDHT * 0.1946472; //80.0;

      HOME_SCREEN_MAINT_BLOCK = HEIGHT * 0.35358445;

      HOME_SCREEN_MAINTITLE = WIDHT * 0.09245742092;
      HOME_SCREEN_SUBTITLE = WIDHT * 0.03649635036 ;
      HOME_SCREEN_LOGOSIZE = WIDHT * 0.15815085158 ;

      HOME_SCREEN_MAIN_CARDWIDTH = HEIGHT * 0.08383961;
      HOME_SCREEN_MAIN_SUBCARDWIDTH = HEIGHT * 0.08505468 + 10;
      HOME_SCREEN_MAIN_BALL_SIZE = HEIGHT * 0.05103281;
      HOME_SCREEN_MAIN_NUMBER_BALL_SIZE = WIDHT * 0.02919708029;


      HOME_SCREEN_MAIN_SUBNUMBER_BALL_SIZE = WIDHT * 0.02433090024;
      HOME_SCREEN_MAIN_SUBBALL_SIZE = HEIGHT * 0.03159174 + 2;
      HOME_SCREEN_OTHERLOTTERYTICKET = WIDHT * 0.04866180048 ;

      HOME_SCREEN_CARDTITLESIZE = WIDHT * 0.02919708029;
      HOME_SCREEN_LISTVIEW_BLOCK = HEIGHT * 0.51032807;
  }
}